name: Build Mac App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip3 install pyinstaller selenium pandas pillow
        brew install chromedriver
    - name: Build app
      run: |
        pyinstaller --onefile --windowed UI_Ready_modified.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mac-app
        path: dist/UI_Ready_modified
#fix: update upload-artifact to v4
